[build]
  command = "CI=false npm install --prefix mernapp --legacy-peer-deps && CI=false npm run build --prefix mernapp"
  publish = "mernapp/build"

[functions]
  directory = "mernapp/backend"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
